%\RequirePackage{ifpdf}
\documentclass[journal]{vgtc}                % final (journal style)
%\documentclass[review,journal]{vgtc}         % review (journal style)

%\usepackage{natbib}
\usepackage[compress,square,comma,numbers]{natbib}
\DeclareRobustCommand{\citeext}[1]{\citeauthor{#1}~\cite{#1}}

\usepackage{mathptmx}
\usepackage{graphicx}
\usepackage{times}
\usepackage{amsmath}
\usepackage{multirow}
\usepackage{caption}
\usepackage{subcaption}
%\usepackage{knitr}
\usepackage{url}
\usepackage[table]{xcolor}

%\definecolor{Blue}{rgb}{0,0,0.5}
\newcommand{\hh}[1]{{\color{magenta} #1}}
\newcommand{\eh}[1]{{\color{red} #1}}
\renewcommand\floatpagefraction{1}


%% declare the category of your paper, only shown in review mode
\vgtccategory{Research}

%% allow for this line if you want the electronic option to work properly
%\vgtcinsertpkg

%% Paper title.

\title{Online logo plots\vspace{-.1in}}

%% indicate IEEE Member or Student Member in form indicated below
\author{Eric Hare and Heike Hofmann and Helga Hofmann-Sieber}
\authorfooter{
%% insert punctuation at end of each item
%\item
Eric Hare is  graduate student of Statistics at Iowa State University, E-mail: erichare@iastate.edu.
%\item

Heike Hofmann is  Professor of Statistics and faculty member in the Human Computer Interaction program at Iowa State University, E-mail: hofmann@iastate.edu.
%\item

Helga Hofmann-Sieber is Post-Doc in Prof Thomas Dobler's group,
Heinrich-Pette-Institute Leibniz Institute for Experimental Virology,
E-mail: helga.hofmann-sieber@hpi.uni-hamburg.de
\vspace{-.1in}}
\setlength\parindent{0pt}

\begin{document}
\maketitle

\hh{
Ok, so let's do a to-do list first:
\begin{enumerate}
\item We need a gentler intro to logo plots and a lit review of them, including the citations coming from the biovis re-design challenge \url{http://www.biovis.net/year/2013/info/redesign-contest}, and the reference to  seqLogo (bioconductor package by \citet{seqlogo})
\item discussion of the cognitive challenges, and our solutions
\item some option of coloring by difference? (this could be based on a comparison of  multinomial distributions)
\end{enumerate}
}

\section{Introduction}


\subsection{The traditional logo plot} 

In a traditional logo sequence plot \citep{logo}, the position of an amino acid in the sequence is plotted on the horizontal axis, while on the vertical axis the amount of preserved information is shown. To measure preservation, Shannon information~\citep{shannon} is used. Shannon information  is an entropy measure given in bits, that describes the amount of mixture in each position. 
Formally, information $I$  in position $p$ is defined as
\[
I(p) = \log_2(21) + \sum_{aa} f_{aa} \log_2(f_{aa}),
\]
where $f_{aa}$ is the relative frequency with which amino acid $aa$ is observed at  position $p$.
For 21 amino acids, the maximal information is $-\log_2 (1/21) = 4.39$ bits, which is reached, if only a single amino acid is observed in the position, while perfect diversity, where all 21 amino acids are observed with the same frequency, results in an information of $0$ bits. 
In the traditional plot, each amino acid is shown in each position by its corresponding letter with its height scaled to reflect the contribution to the position's total information. 

\hh{Here'd be a good place to include a traditional logo plot.}

\subsection{Shortcomings of the traditional logo plot}
%
The {\bf color choice} for representing the letters of amino acids is related to water solubility and polarity (e.g.\ hydrophobic, non-polar amino acids are shown in red) but this is not explicitly stated in a legend. Further, the use of letters to represent amino acids results in shapes of different visual dominance; the letter `I' is much less visually pronounced than for example `W'.\\

\hh{This has also the potential of leading to ambiguity in the representation: e.g.\~using the standard Helvetica representation, the letter F over a T is not (easily) distinguishable from a letter E over an I.}

{\bf Non identified amino acids} are being ignored in the original plot -- it is of importance to keep track of at least the position  and the frequency of these occurrences, as it might indicate a problem with the sequencing.\\

The plotting of {\bf sequences of subfamilies} in separate logo plots does not facilitate a comparison of them. Researchers are in particular interested in differences in the conservation of amino acids between subfamilies.\\

The {\bf number of sequences} in each of the subfamilies is not shown directly. This influences  the inherent variability. It is therefore important to keep track of these numbers to be able to assess how and whether the size of each subfamily affects conservation.
%
\subsection{Aspects of the redesign}

\hh{We will highlight aspects of the re-design using data made available as part of the BioVis 2013 re-design challenge (see  \url{http://www.biovis.net/year/2013/info/redesign-contest})}. The data consists of 1809 protein sequences of length 36 that are either Gram-negative (923 sequences) or  Gram-positive (886 sequences). Figure~\ref{fig:1} shows logo plots featuring this data using the re-design discussed in this section.

 We focused on a re-design of the logo plot that will allow to easily answer the following three questions: 
\begin{enumerate} %\itemsep-.05in
\item[\bf (i)] {\it How well do the observed sequences conserve the overall pattern?} 
\item[\bf (ii)] {\it  What are differences in the conservation of the main pattern  between different types of treatment or strains?}  For this particular data set: what are the differences between Gram-positive and Gram-negative sequences?
\item[\bf (iii)] {\it What are the important positions and amino acids between the different treatments or strains?} Here, this translates to the question of which amino acids are important for Gram-positive sequences, which for Gram-negative.
\end{enumerate}
% non identified amino acids
\subsubsection{Putting the letters in a box}
The visually most dominant change to the display is the addition of boxes framing each letter. This gives each amino acid visually the same weight, independent of the shape of its corresponding letter. We decided to keep the letters themselves since they incorporate valuable and immediately recognizable information in the display.
% Construction of the plot
The height of boxes and letters is still given by the contribution of the amino acids to the total information. 
The width of boxes is adjusted for the number of sequences in each subfamily, if appropriate. In Figure~\ref{fig:1b} this difference is not immediately visible, as the class sizes are very similar, but in case of very different class sizes a rescaling of the width is extremely helpful.

As information is strictly non-negative, we can make further use of the vertical axis by aligning the bottom of the box for the most frequently observed amino acid along the horizontal axis. This makes the box heights for the top sequence directly comparable.  It also aligns the boxes for the second most frequent amino acid, enabling comparisons of either one of the two highest contributions along a common scale \citep{cleveland:1984}. This reveals a previously unnoticed subgroup in the Gram-positive bacteria.  103 out of the 886 Gram-positive bacteria stabilize their  ADK lid domain in the same way as Gram-negative bacteria using a hydrogen bonding network between residues 4, 7, 9, 24, 27, and 29.


\subsubsection{Color \& Shade}
Color hues are used to show two main properties of amino acids: polarity and electrical charging. Non-polar amino acids are shown in grey, polar amino acids are divided into positively charged (red), negatively charged (blue) and uncharged (yellow) amino acids. In contrast to the original plot a legend is included in the graphic. This makes it easier for the reader to identify possible interactions between polar residues at first view.



\subsubsection{Treatment of non-identified amino acids}
Another change to the original design is that non-identified amino acids (marked by a `.' in the  sequence) are kept, and shown in the visualization by a framed, but otherwise transparent box. The Shannon information calculated for the collective of non-identified amino acids should not be interpreted as actual information, as non-identified amino acids are not necessarily the same, but the fact, that amino acids are not identified in a position is valuable and should not be ignored. For example,  non-identified amino acids contribute the second largest contingent among the Gram-positive sequences in position 28, and might be an explanation of why these sequences are not conserved as well as  Gram-negative ones.

\subsubsection{Covariates in logos: Juxtaposition of subfamilies}
In order to facilitate comparisons across subfamilies, boxes of amino acids from different families are positioned side-by-side as shown in figure~\ref{fig:1b} to emphasize differences between Gram-positive and Gram-negative sequences. In a further step (not shown) this can be used to show sub-classes or clusters of sequences within a subfamily, which would represent a logical next step of an analysis and allow for an evaluation of how often and in which positions amino acids deviate from the main sequence structure. 

\subsection{Our Implementation}
Our re-design is implemented as a Shiny-based web application, using the R statistical software. It is available at the URL \url{http://erichare.shinyapps.io/gglogo}. The software allows users to input sequencing data in the FASTA format, or upload a FASTA file. The resulting logo plot will be displayed on the right, with a slider to adjust the visible region of the plot. A button for downloading the plot as a file is displayed on the left.

\hh{Each one of the items on the list should become a subsubsection with a screenshot zoomed into the corresponding part of the discussion.}
Several advanced options are available after clicking ``Show Advanced Configuration":

\begin{itemize}
    \item A facetting variable can be selected, which will show multiple logo plots based on the metadata contained in the FASTA file.
    \hh{here, we need to discuss what facetting is - and how it is possible to encode a facetting variable in a FASTA file. }
    \item The plot groups can be defined. The name of the group, and the color of the amino acids for that group in the logo plut can be selected.
    \hh{plot groups is the code internal name, right? what the user sees is the color, so just flip the order of the description and start with color for different amino acids based on different ways of grouping them - can we already link to the amino acid database? If not, let's include that in the conclusions under future work. }
    
    \item A plot title, x axis label, and y axis label can be provided.
    \hh{these are all options of directly manipulating the resulting logoplot in the browser. the header of this section should be something like that.}
    
    \item \hh{`Saving the result' ? } The image format for downloading the image can be selected as either png, jpg, or pdf. 
    \item The DPI (dots per inch) of the image can be defined. \hh{this should be included as an option in the last item}
\end{itemize}

\begin{figure*}
\begin{subfigure}[b]{\linewidth}
\caption{Sequence logos showing the amino acid usage in the adenylate kinase lid (AKL) domain across all organisms.}\label{fig:1a} 
<<redesign, results='asis',  echo=FALSE, out.width='\\textwidth', fig.width=9, fig.height=4, message=FALSE>>=
## To install gglogo
# library(devtools)
# install_github("heike/gglogo")
library(gglogo)
library(scales)
library(grid)
library(ggplot2)
library(RColorBrewer)

data(sequences)
data(aacids)

dm2 <- splitSequence(sequences, "peptide")
cols <- c("grey80", brewer.pal(3,"RdYlBu"))

dm3 <- calcInformation(dm2, pos="position", elems="element", k=21)
dm3b <- merge(dm3, aacids, by.x="element", by.y="AA", all.x=T)
ggplot(dm3b, aes(x=position, y=bits, group=element, label=element, fill=Polarity), alpha=0.8) + geom_hline(yintercept=-log(1/21, base=2), colour="grey30", size=0.5) + geom_logo() + scale_fill_manual("Polarity", values=cols) +  theme_bw() + theme(legend.position="bottom") + ylab("bits") + theme(plot.margin=unit(c(0,0,0,0), "cm")) + geom_hline(yintercept=0, colour="white", size=0.5) + geom_hline(yintercept=0, colour="grey30", size=0.125) + scale_y_continuous(breaks=c(-1,0,1,2,4), labels=c(1,0,1,2,4))
@
\end{subfigure}% 
\hfill

\begin{subfigure}[b]{\linewidth}
\caption{Juxtaposition of amino acid usage in the adenylate kinase lid (AKL) domain of Gram-positive and Gram-negative bacteria \hfill}\label{fig:1b} 
<<redesign-byclass, results='asis', echo=FALSE, out.width='\\textwidth', fig.width=9, fig.height=4.5>>=
dm4 <- calcInformation(dm2, pos="position", elems="element", trt="class", k=21)
dm5 <- merge(dm4, aacids, by.x="element", by.y="AA", all.x=T)
dm4b <- as.data.frame(xtabs(freq ~class, data=dm4)/36)
names(dm4b)[2] <- "width"
dm5b <- merge(dm5, dm4b, by="class")
dm5b$width <- 0.95*dm5b$width/max(dm5b$width)
levels(dm5b$class) <- c("-", "+")

ggplot(dm5b, aes(x=class, y=bits, group=element, label=element, fill= Polarity), alpha=0.8) + geom_hline(yintercept=-log(1/21, base=2), colour="grey30", size=0.5) + geom_logo(aes(width=width)) + scale_fill_manual("Polarity", values=cols, guide=guide_legend(nrow=2)) + facet_wrap(~position, nrow=2) + theme_bw() + theme(legend.position="none") + xlab("") + ylab("bits")  + theme(plot.margin=unit(c(0,0,0,0), "cm")) + geom_hline(yintercept=0, colour="white", size=0.5) + geom_hline(yintercept=0, colour="grey30", size=0.125) + scale_y_continuous(breaks=c(-1,0,1,2,4), labels=c(1,0,1,2,4))
@
\end{subfigure} 
\caption{ 
The ADK lid domain structure is universally conserved, but is stabilized in the Gram-negatives by a hydrogen bonding network between residues 4, 7, 9, 24, 27, and 29 (and several other residues in some organisms), while the Gram-positives are stabilized by a bound metal ion, tetrahedrally coordinated by four Cysteine residues at 4, 7, 24 and 27. A percentage of 11.6\% ($\pm 2.2$) Gram-positive bacteria stabilizes their ADK lid domain in the same way as Gram-negative bacteria using a hydrogen bonding network between residues 4, 7, 9, 24, 27, and 29.
The identities of several other positions (eg 5, 8, 30, 32) are differentially constrained in each subfamily as well, apparently due to steric requirements of the stabilizing residues.
}\label{fig:1}
\end{figure*}

\section{Online tools}
\begin{itemize}
\item RWebLogo R Code, wrapper for python code (BSD licence) \cite{rweblogo}
\item WebLogo Python Code Python Code (BSD license, somewhat difficult to use)
\item WebLogo 3.0 \cite{weblogo}
\item Seq2Logo \cite{seq2logo} (Online app. for peptide alignments feat. pseudo count, sequence weighting and two-sided representation)
\item MoRAine (Online application with integrated binding site re-annotation) \cite{moraine}
\item GENIO (Online, \url{http://www.biogenio.com/logo/} - no other apparent reference)
\item PWM-based logo (Online application for motif PWM-based models) - XXX can't find an appropriate reference
\item LogoBar \cite{logobar} (Java application)
\item CorreLogo \cite{correlogo} An online server for 3D sequence logos of RNA and DNA alignments
\item seqLogo \cite{seqlogo} C function to generate DNA sequence logos (the reference is for the R package. I am not sure that there are C functions)
\item MS-Word AddOn Ribbon that allows generation of consensus logos - can't find a reference besides to http://sourceforge.net/projects/bioword/?source=navbar
\item RILogo program and web server \cite{rilogo} for creating logos for two interacting RNAs
\item Skylign Online tool  \cite{skylign} for creating logos representing both sequence alignments and profile hidden Markov models
\end{itemize}
\bibliographystyle{natbib}
% argument is your BibTeX string definitions and bibliography database(s)
\bibliography{references}


\end{document}

% <<fig3>>=
% dseq <- seqtree(subset(sequences, class=="gram +")$peptide, pos=c(4,7,24,27), k=2)
% dseq$class <- "gram +"
% sequences$cl <- 3
% sequences$Freq <- 1
% names(sequences)[1] <- "subseq"
% dseq <- rbind(dseq, sequences)
% dm2 <- splitSequence(dseq, "subseq")
% dm3 <- calcInformation(dm2, pos="position", trt="cl", elems="element", k=21, weight="Freq")
% library(RColorBrewer)
% cols <- c("grey80", brewer.pal(3,"RdYlBu"))
% data(aacids)
% dm3b <- merge(dm3, aacids, by.x="element", by.y="AA", all.x=T)
% dm3c <- as.data.frame(xtabs(Freq ~cl, data=dm2)/36)
% names(dm3c)[2] <- "width"
% dm3b <- merge(dm3b, dm3c, by="cl")
% dm3b$width <- dm3b$width/max(dm3b$width)
% ggplot(dm3b, aes(x=cl, y=bits, group=element, label=element, fill=Polarity)) + theme_bw() + geom_logo(aes(width=width)) + scale_fill_manual(values=cols) + facet_wrap(~position) + scale_x_continuous(limits=c(0.5,3.5))
% @
